spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/localdb
    username: postgres
    password: secret
    driver-class-name: "org.postgresql.Driver"
    hikari:
      schema: "transaction_events"