project:
  name: "transaction-api-service"
  version: "1.0.0-SNAPSHOT"
  description: "Simple Spring Boot Service Project."

spring:
  application:
    name: ${project.name}
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
