apiVersion: v1
kind: Secret
metadata:
  name: transaction-api-service-secret
type: Opaque
stringData:
  DATABASE_URL: jdbc:postgresql://postgres:5432/localdb
  DATABASE_USERNAME: ocpuser
  DATABASE_PASSWORD: secret
  SPRING_PROFILES_ACTIVE: dev
